nginx:
    build: ./nginx
    links:
        - server1:server1
        - server2:server2
        - server3:server3
    ports:
        - "80:80"
server1:
    build: ./server
    links:
        - redis
    ports:
        - "8080"
server2:
    build: ./server
    links:
        - redis
    ports:
        - "8080"
server3:
    build: ./server
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"