version: '2'

services:
    web:
        build: ./nginx
        ports:
            - "8080:80"
        volumes:
            - ./src:/srv/src
            - ./src/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: ./php
        volumes:
            - ./src:/srv/src
        networks:
            - code-network

networks:
    code-network:
        driver: bridge